FROM ruby:2.4

RUN apt-get update -yqq && \
    apt-get install --yes apt-utils && \
    apt-get install --yes curl && \
    apt-get install --yes build-essential && \
    apt-get install libsasl2-dev nano && \
    gem install bundler:2.1.4 && \
    curl --silent --location https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get install --yes nodejs

ADD Gemfile* /app/
WORKDIR /app
ADD . /app

ENTRYPOINT ["bin/docker_entrypoint.sh"]