version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    command: ./bin/docker_entrypoint.sh server
    volumes:
      - .:/app
      - ./bundle_cache:/usr/local/bundle
      - ./node_modules:/usr/lib/node_modules/
    environment: 
      DATABASE_PASSWORD: root
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - ./tmp/db:/var/lib/postgresql/data